Repository json-schema-org/website, pull requests merged in 2024-08, with the labels that each got.

#807 Feat: Adding next-prev component
  components/NextPrevButton.tsx
  pages/learn/[slug].page.tsx
  pages/learn/file-system.md
  pages/learn/getting-started-step-by-step.md
  pages/learn/json-schema-examples.md
  pages/learn/miscellaneous-examples.md
  public/icons/arrow.svg
Labels: GSoD

#842 chore(yarn) : migrated yarn to modern yarn berry
  .github/workflows/build-preview.yml
  .github/workflows/ci.yml
  .github/workflows/link-checker.yml
  .github/workflows/production-deployment.yml
  .gitignore
  .yarnrc.yml
  README.md
  package.json
  yarn.lock
Labels: GSoC

#838 Add workflow to update landscape tooling
  .github/workflows/trigger-update-landscape-tooling.yml
Labels: GSoC

#858 [pages][tools]: Implement Tooling Analytics and Integrate Bowtie Report
  .github/ISSUE_TEMPLATE/adding-your-tooling.yml
  .github/workflows/trigger-update-landscape-tooling.yml
  components/Layout.tsx
  data/tooling-data.yaml
  next.config.js
  package.json
  pages/blog/posts/and-then-there-were-three.md
  pages/blog/posts/applicability-json-schema-fundamentals-part-1.md
  pages/blog/posts/bowtie-intro.md
  pages/blog/posts/get-started-with-json-schema-in-node-js.md
  pages/blog/posts/json-schema-in-5-minutes.md
  pages/implementers/interfaces.md
  pages/index.page.tsx
  pages/learn/getting-started-step-by-step/getting-started-step-by-step.md
  pages/learn/getting-started-step-by-step/next-steps.md
  pages/overview/what-is-jsonschema.md
  pages/tools/JSONSchemaTool.ts
  pages/tools/components/GroupByMenu.tsx
  pages/tools/components/GroupBySelector.tsx
  pages/tools/components/SearchBar.tsx
  pages/tools/components/Sidebar.tsx
  pages/tools/components/ToolingDetailModal.tsx
  pages/tools/components/ToolingTable.tsx
  pages/tools/components/ToolingTable/TableCell.tsx
  pages/tools/components/ToolingTable/TableColumnHeader.tsx
  pages/tools/components/ToolingTable/TableSortableColumnHeader.tsx
  pages/tools/components/ToolingTable/ToolingTable.tsx
  pages/tools/components/ui/Checkbox.tsx
  pages/tools/components/ui/DropdownMenu.tsx
  pages/tools/hooks/usePreferences.tsx
  pages/tools/hooks/useToolsTransform.tsx
  pages/tools/index.page.tsx
  pages/tools/lib/analytics.schema.json
  pages/tools/lib/getDistinctEntries.ts
  pages/tools/lib/getQueryParamValues.ts
  pages/tools/lib/getUniqueValuesPerField.ts
  pages/tools/lib/postAnalytics.ts
  pages/understanding-json-schema/_index.md
  public/_redirects
  public/icons/filter-dark.svg
  public/icons/filter.svg
  public/icons/outlink.svg
  public/img/tools/logos/json-everything.svg
  svgr.d.ts
  tsconfig.json
  yarn.lock
Labels: GSoC

#869 chore(github-actions): update contributor and project sync workflows
  .github/workflows/sync-contributors.yml
  .github/workflows/sync-project-roadmap.yml
Labels: 🐛 Bug, github_actions

#870 testing(component-testing) : Add component test
  components/Accordion.tsx
  components/Code.tsx
  components/DarkModeToggle.tsx
  components/DocsHelp.tsx
  components/Headlines.tsx
  components/JsonEditor.tsx
  components/Remember.tsx
  components/ScrollButton.tsx
  components/jsonSchemaLinks.ts
  cypress/components/Accordian.cy.tsx
  cypress/components/Code.cy.tsx
  cypress/components/DarkModeToggle.cy.tsx
  cypress/components/DocsHelp.cy.tsx
  cypress/components/Faq.cy.tsx
  cypress/components/Headlines.cy.tsx
  cypress/components/JsonEditor.cy.tsx
  cypress/components/Remember.cy.tsx
  cypress/components/ScrollButton.cy.tsx
  cypress/plugins/mockNextRouterUtils.ts
Labels: GSoC

#844 feat: adding keywords page
  components/Sidebar.tsx
  data/keywords.yml
  pages/understanding-json-schema/keywords/index.page.tsx
  public/icons/external-link.svg
Labels: Status: In Progress, GSoD
