Repository json-schema-org/website, pull requests merged in 2024-03, with the labels that each got.

#384 Changing .xml to .md
  pages/specification-links.md
Labels: Status: Review Needed

#382 Adding Openapi Links
  pages/implementations/main.md
Labels: Status: Review Needed

#332 Removed Warnings
  pages/blog/posts/[slug].page.tsx
Labels: Status: Completed

#387 Adding Docker Setup
  .dockerignore
  Dockerfile
  README.md
  makefile
Labels: Status: Completed

#390 feat: Add links to similar technologies (#126)
  components/Sidebar.tsx
  pages/overview/similar-technologies.md
Labels: Status: Review Needed

#383 feature: setup husky, prettier and eslint
  .eslintrc.js
  .husky/pre-commit
  .prettierignore
  .prettierrc
  README.md
  components/CarbonsAds.tsx
  components/Code.tsx
  components/DocsHelp.tsx
  components/Headlines.tsx
  components/JsonEditor.tsx
  components/Layout.tsx
  components/Remember.tsx
  components/Sidebar.tsx
  components/SiteLayout.tsx
  components/StyledMarkdown.tsx
  components/jsonSchemaLinks.ts
  context.ts
  lib/config.ts
  lib/getFindResultsByGlobalRegExp.ts
  lib/getPartsOfJson.ts
  lib/getScopesOfParsedJsonSchema.ts
  lib/getStaticMarkdownPaths.ts
  lib/getStaticMarkdownProps.ts
  lib/getStaticPropsFromSingleMarkdown.ts
  lib/slugifyMarkdownHeadline.ts
  lib/useSetUrlParam.ts
  package.json
  pages/[slug].page.tsx
  pages/_app.page.tsx
  pages/_document.page.tsx
  pages/blog/generateRssFeed.tsx
  pages/blog/index.page.tsx
  pages/blog/posts/[slug].page.tsx
  pages/draft-05/[slug].page.tsx
  pages/draft-06/[slug].page.tsx
  pages/draft-07/[slug].page.tsx
  pages/draft/2019-09/[slug].page.tsx
  pages/draft/2020-12/[slug].page.tsx
  pages/implementations/index.page.tsx
  pages/implementers/[slug].page.tsx
  pages/implementers/index.page.tsx
  pages/index.page.tsx
  pages/learn/[slug].page.tsx
  pages/managed-mixed-page/index.page.tsx
  pages/obsolete-implementations/index.page.tsx
  pages/overview/[slug].page.tsx
  pages/overview/code-of-conduct/index.page.tsx
  pages/overview/sponsors/index.page.tsx
  pages/understanding-json-schema/[slug].page.tsx
  pages/understanding-json-schema/index.page.tsx
  pages/understanding-json-schema/reference/[slug].page.tsx
  pages/understanding-json-schema/reference/index.page.tsx
  public/understanding/jsonschema.css
  store.ts
  styles/globals.css
  tsconfig.json
  yarn.lock
Labels: Status: Completed

#325 fixed lazy expression issue
  pages/understanding-json-schema/reference/regular_expressions.md
Labels: Status: Completed

#342 ci: added triage labels for issues
  .github/issue-labler.yml
  .github/workflows/issue-labeler.yml
Labels: Status: Completed

#357 Add Resolves/Closes Keywords and updated PR Template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/pull_request_template.md
Labels: Status: Completed

#386 added dates to specification link
  pages/specification-links.md
Labels: Status: Review Needed

#405 docs: added definition of json hyper-schema
  pages/learn/glossary.md
Labels: Status: Completed

#362 Doc: Custom markdown style guide
  CONTRIBUTING.md
  pages/md-style-guide.md
Labels: Status: In Progress

#353 ci: add workflow to welcome first-time contributors
  .github/workflows/welcome-first-time-contrib.yml
Labels: Status: Review Needed

#385 resolved code formatting issue #371
  pages/draft/2020-12/release-notes.md
Labels: Status: In Progress
