Repository json-schema-org/website, pull requests merged in 2024-05, with the labels that each got.

#527 Enhancement: use env vars instead of hardcoded credentials
  .env.example
  components/Layout.tsx
  pages/index.page.tsx
Labels: Status: On Hold

#679 Restructure what is JSON Schema for clarity
  pages/overview/what-is-jsonschema.md
  public/img/json_schema.svg
Labels: Status: In Progress

#695 Enhancement : Merge both greet-on-first-pr and merge in pull-request-target-yml
  .github/issue-labeler.yml
  .github/workflows/greet_on_first_merge.yml
  .github/workflows/issue-labeler.yml
  .github/workflows/pull-request-target.yml
  .github/workflows/welcome-first-time-contrib.yml
Labels: GSoC

#693 Feature: Added Issue-yml
  .github/workflows/issue.yml
Labels: GSoC

#700 WEB-R-3: Moving resources to new branch
  components/Sidebar.tsx
  data/resources.yml
  pages/resources/[slug].page.tsx
  public/icons/bookshelf-dark.svg
  public/icons/bookshelf.svg
Labels: GSoD

#698 Feat: Removing resources and newletter from web-release-3 branch
  components/Newsletter.tsx
  components/Sidebar.tsx
  data/resources.yml
  pages/newsletter/index.page.tsx
  pages/resources/[slug].page.tsx
  public/icons/bookshelf-dark.svg
  public/icons/bookshelf.svg
Labels: GSoD

#705 Feat: Table of content component design change
  components/StyledMarkdown.tsx
Labels: GSoD

#690 Feature : github-actions - Setup stale Issues and PRs workflow
  .github/workflows/stale.yml
Labels: GSoC

#721 Fix: ToC blog page fix
  components/Sidebar.tsx
  components/StyledMarkdown.tsx
  pages/blog/posts/[slug].page.tsx
  pages/blog/posts/understanding-lexical-dynamic-scopes.md
Labels: GSoD
